export const leagueCodes = {
  "afc.asian": "AFC Asian Cup",
  "afc.asianq": "AFC Asian Cup Qualifiers",
  "afc.champions.elite": "AFC Champions League Elite",
  "afc.champions.two": "AFC Champions League Two",
  "aff.cup": "ASEAN Championship",
  "arg.1": "Argentine Liga Profesional de Fútbol",
  "arg.2": "Argentine Nacional B",
  "arg.3a": "Argentine Primera B",
  "arg.3b": "Argentine Primera C",
  "arg.cup": "Copa Argentina",
  "aut.1": "Austrian Bundesliga",
  "aus.1": "Australian A-League Men",
  "aus.w.1": "Australian A-League Women",
  "bel.1": "Belgian Pro League",
  "bol.1": "Bolivian Liga Profesional",
  "bra.1": "Brazilian Serie A",
  "bra.2": "Brazilian Serie B",
  "bra.3": "Brazilian Serie C",
  "bra.carioca": "Brazilian Campeonato Carioca",
  "bra.cup": "Copa do Brasil",
  "bra.gaucho": "Brazilian Campeonato Gaucho",
  "bra.mineiro": "Brazilian Campeonato Mineiro",
  "bra.paulista": "Brazilian Campeonato Paulista",
  "caf.champions": "CAF Champions League",
  "caf.confederation": "CAF Confederation Cup",
  "caf.chan": "African Nations Championship",
  "caf.nations": "Africa Cup of Nations",
  "caf.nationsq": "Africa Cup of Nations Qualifying",
  "caf.wnations": "Women's Africa Cup of Nations",
  "can.nsl": "Northern Super League",
  "chi.1": "Chilean Primera División",
  "chi.cup": "Copa Chile",
  "chn.1": "Chinese Super League",
  "col.1": "Colombian Primera A",
  "col.2": "Colombian Primera B",
  "col.cup": "Copa Colombia",
  "concacaf.champions": "Concacaf Champions Cup",
  "concacaf.central.cup": "Concacaf Central American Cup",
  "concacaf.gold": "Concacaf Gold Cup",
  "concacaf.leagues.cup": "Leagues Cup",
  "concacaf.nations": "Concacaf Nations League",
  "concacaf.wchampionship": "Concacaf W Championship",
  "concacaf.w.champions": "Concacaf W Champions Cup",
  "concacaf.wgold": "Concacaf W Gold Cup",
  "conmebol.copa.america": "Copa América",
  "conmebol.copa.america.f": "Copa América Femenina",
  "conmebol.libertadores": "CONMEBOL Libertadores",
  "conmebol.sudamericana": "CONMEBOL Sudamericana",
  "crc.1": "Costa Rican Primera Division",
  "cyp.1": "Cypriot First Division",
  "den.1": "Danish Superliga",
  "ecu.1": "LigaPro Ecuador",
  "eng.1": "English Premier League",
  "eng.2": "English League Championship",
  "eng.3": "English League One",
  "eng.4": "English League Two",
  "eng.efl.trophy": "English EFL Trophy",
  "eng.fa": "English FA Cup",
  "eng.league_cup": "English Carabao Cup",
  "eng.natl": "English National League",
  "eng.w.1": "English Women's Super League",
  "eng.w.fa": "English Women's FA Cup",
  "esp.1": "Spanish LALIGA",
  "esp.2": "Spanish LALIGA 2",
  "esp.copa": "Spanish Copa del Rey",
  "esp.w.1": "Spanish Liga F",
  "esp.w.copa": "Spanish Copa de la Reina",
  "fifa.club": "FIFA Club World Cup",
  "fifa.friendly": "International Friendly",
  "fifa.friendly.w": "Women's International Friendly",
  "fifa.inter.cup": "FIFA Intercontinental Cup",
  "fifa.olymp.m": "Men's Olympic Soccer Tournament",
  "fifa.olymp.w": "Women's Olympic Soccer Tournament",
  "fifa.u17": "FIFA Under-17 World Cup",
  "fifa.u20": "FIFA Under-20 World Cup",
  "fifa.world": "FIFA World Cup",
  "fifa.worldq.afc": "FIFA World Cup Qualifying - AFC",
  "fifa.worldq.caf": "FIFA World Cup Qualifying - CAF",
  "fifa.worldq.concacaf": "FIFA World Cup Qualifying - Concacaf",
  "fifa.worldq.conmebol": "FIFA World Cup Qualifying - CONMEBOL",
  "fifa.worldq.ofc": "FIFA World Cup Qualifying - OFC",
  "fifa.worldq.uefa": "FIFA World Cup Qualifying - UEFA",
  "fifa.wwcq.uefa": "FIFA Women's World Cup Qualifying - UEFA",
  "fifa.wworld": "FIFA Women's World Cup",
  "fifa.wu17": "FIFA Under-17 Women's World Cup",
  "fra.1": "French Ligue 1",
  "fra.2": "French Ligue 2",
  "fra.cup": "Coupe de France",
  "fra.w.1": "French Première Ligue",
  "ger.1": "German Bundesliga",
  "ger.2": "German 2. Bundesliga",
  "ger.pokal": "German Cup",
  "gre.1": "Greek Super League",
  "gua.1": "Guatemalan Liga Nacional",
  "hon.1": "Honduran Liga Nacional", // Not in List A
  "ind.1": "Indian I-League",
  "idn.1": "Indonesian Super League", // Not in List A
  "irl.1": "Irish Premier Division",
  "ita.1": "Italian Serie A",
  "ita.2": "Italian Serie B",
  "ita.coppa": "Coppa Italia",
  "jpn.1": "Japanese J.League",
  "ksa.1": "Saudi Pro League",
  "ken.1": "Kenyan Premier League", // Not in List A
  "mas.1": "Malaysian Super League", // Not in List A
  "mau.revello": "Maurice Revello Tournament",
  "mex.1": "Mexican Liga BBVA MX",
  "mex.2": "Mexican Liga de Expansión MX",
  "ncaa.m": "NCAA Men's Soccer",
  "ncaa.w": "NCAA Women's Soccer",
  "ned.1": "Dutch Eredivisie",
  "ned.2": "Dutch Keuken Kampioen Divisie",
  "ned.cup": "Dutch KNVB Beker",
  "ned.w.1": "Dutch Vrouwen Eredivisie",
  "ned.w.cup": "Dutch KNVB Beker Vrouwen",
  "nga.1": "Nigerian Professional League", // Not in List A
  "nor.1": "Norwegian Eliteserien",
  "par.1": "Paraguayan Primera División",
  "per.1": "Peruvian Liga 1",
  "pinatar.cup": "Pinatar Cup",
  "por.1": "Portuguese Primeira Liga",
  "por.cup": "Taca de Portugal",
  "rsa.1": "South African Premiership",
  "rsa.2": "South African First Division",
  "rsa.mtn8": "South African MTN 8 Cup",
  "rus.1": "Russian Premier League",
  "saff.cup": "SAFF Championship",
  "sco.1": "Scottish Premiership",
  "sco.2": "Scottish Championship",
  "sco.chalg.cup": "Scottish League Challenge Cup",
  "sco.cup": "Scottish Cup",
  "sco.league_cup": "Scottish League Cup",
  "shebelieves.cup": "SheBelieves Cup",
  "sin.1": "Singaporean Premier League", // Not in List A
  "slv.1": "Salvadoran Primera Division",
  "swe.1": "Swedish Allsvenskan",
  "tha.1": "Thai League 1", // Not in List A
  "tur.1": "Turkish Super Lig",
  "uefa.champions": "UEFA Champions League",
  "uefa.champions.q": "UEFA Champions League Qualifying",
  "uefa.euro": "UEFA European Championship",
  "uefa.euroq": "UEFA European Championship Qualifying",
  "uefa.europa": "UEFA Europa League",
  "uefa.europa.conf": "UEFA Conference League",
  "uefa.europa.conf.q": "UEFA Conference League Qualifying",
  "uefa.europa.q": "UEFA Europa League Qualifying",
  "uefa.nations": "UEFA Nations League",
  "uefa.u19": "UEFA European Under-19 Championship",
  "uefa.u21": "UEFA European Under-21 Championship",
  "uefa.u21.q": "UEFA European Under-21 Championship Qualifying",
  "uefa.w.nations": "UEFA Women's Nations League",
  "uefa.wchampions": "UEFA Women's Champions League",
  "uefa.weuro": "UEFA Women's European Championship",
  "uga.1": "Ugandan Premier League", // Not in List A
  "uru.1": "Liga AUF Uruguaya",
  "usa.1": "MLS",
  "usa.nwsl": "NWSL",
  "usa.nwsl.challenge.cup": "NWSL Challenge Cup",
  "usa.usl": "USL Championship",
  "usa.usl.jagermeister.cup": "USL Jägermeister Cup",
  "usa.usl.l1": "USL League One",
  "usa.usl.super": "USL Super League",
  "usa.usopen": "U.S. Open Cup",
  "ven.1": "Venezuelan Primera División", // Not in List A
}